-- Add missing columns to financial_years table
ALTER TABLE financial_years 
ADD COLUMN IF NOT EXISTS year_name VARCHAR(50),
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS savings_interest_rate DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS loan_interest_rate DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS created_by UUID,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
