const { ReportService } = require('./src/services/ReportService');
const { PDFReportGenerator } = require('./src/services/PDFReportGenerator');

async function testComprehensiveReport() {
  try {
    console.log('Testing Comprehensive Financial Summary Report...\n');
    
    // Generate report for last 30 days
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - 30);
    
    console.log(`Generating report for period: ${startDate.toLocaleDateString()} to ${endDate.toLocaleDateString()}`);
    
    const reportData = await ReportService.generateComprehensiveFinancialSummaryReport(
      startDate,
      endDate,
      'System Test'
    );
    
    console.log('Report generated successfully!');
    console.log(`Title: ${reportData.title}`);
    console.log(`Generated By: ${reportData.generatedBy}`);
    console.log(`Report Type: ${reportData.reportType}`);
    console.log(`Generated Date: ${reportData.generatedDate.toLocaleString()}`);
    
    // Display summary
    console.log('\n=== REPORT SUMMARY ===');
    console.log(`Total Fund Value: R ${reportData.summary.totalFundValue.toLocaleString()}`);
    console.log(`Total Members: ${reportData.summary.totalMembers}`);
    console.log(`Active Members: ${reportData.summary.activeMembers}`);
    console.log(`Total Contributions: R ${reportData.summary.totalContributions.toLocaleString()}`);
    console.log(`Total Outstanding: R ${reportData.summary.totalOutstanding.toLocaleString()}`);
    console.log(`Net Cash Flow: R ${reportData.summary.netCashFlow.toLocaleString()}`);
    console.log(`Net Interest: R ${reportData.summary.netInterest.toLocaleString()}`);
    console.log(`Financial Health: ${reportData.summary.financialHealth}`);
    
    // Generate HTML
    console.log('\n=== GENERATING HTML REPORT ===');
    const htmlContent = PDFReportGenerator.generateComprehensiveFinancialSummaryHTML(reportData);
    console.log(`HTML content generated (${htmlContent.length} characters)`);
    
    // Generate CSV
    console.log('\n=== GENERATING CSV REPORT ===');
    const csvContent = ReportService.exportToCSV(reportData);
    console.log(`CSV content generated (${csvContent.length} characters)`);
    
    // Display sample of CSV
    console.log('\n=== CSV SAMPLE (first 500 chars) ===');
    console.log(csvContent.substring(0, 500) + '...');
    
    // Display key metrics from data
    console.log('\n=== KEY METRICS ===');
    console.log('Fund Overview:');
    console.log(`  - Total Fund Value: R ${reportData.data.fundOverview.totalFundValue.toLocaleString()}`);
    console.log(`  - Total Members: ${reportData.data.fundOverview.totalMembers}`);
    console.log(`  - Active Members: ${reportData.data.fundOverview.activeMembers}`);
    console.log(`  - Member Participation Rate: ${reportData.data.fundOverview.memberParticipationRate}%`);
    console.log(`  - Contribution Compliance Rate: ${reportData.data.fundOverview.contributionComplianceRate}%`);
    
    console.log('\nTransaction Summary:');
    console.log(`  - Total Deposits: R ${reportData.data.transactionSummary.totalDeposits.toLocaleString()}`);
    console.log(`  - Total Withdrawals: R ${reportData.data.transactionSummary.totalWithdrawals.toLocaleString()}`);
    console.log(`  - Total Loan Repayments: R ${reportData.data.transactionSummary.totalLoanRepayments.toLocaleString()}`);
    console.log(`  - Net Cash Flow: R ${reportData.data.transactionSummary.netCashFlow.toLocaleString()}`);
    
    console.log('\nInterest Summary:');
    console.log(`  - Interest Earned: R ${reportData.data.interestSummary.totalInterestEarned.toLocaleString()}`);
    console.log(`  - Interest Charged: R ${reportData.data.interestSummary.totalInterestCharged.toLocaleString()}`);
    console.log(`  - Net Interest: R ${reportData.data.interestSummary.netInterest.toLocaleString()}`);
    console.log(`  - Average Interest Rate: ${reportData.data.interestSummary.averageInterestRate}%`);
    
    console.log('\nMember Standing:');
    console.log(`  - Good Standing: ${reportData.data.memberStanding.good}`);
    console.log(`  - Owing 10%: ${reportData.data.memberStanding.owing_10}`);
    console.log(`  - Owing 20%: ${reportData.data.memberStanding.owing_20}`);
    console.log(`  - Owing 30%: ${reportData.data.memberStanding.owing_30}`);
    console.log(`  - Owing 50%: ${reportData.data.memberStanding.owing_50}`);
    console.log(`  - Owing 65%: ${reportData.data.memberStanding.owing_65}`);
    console.log(`  - Owing 65%+: ${reportData.data.memberStanding.owing_65_plus}`);
    
    console.log('\nFinancial Ratios:');
    console.log(`  - Liquidity Ratio: ${reportData.data.financialRatios.liquidityRatio}`);
    console.log(`  - Risk Exposure: ${reportData.data.financialRatios.riskExposure}%`);
    console.log(`  - Contribution Compliance Rate: ${reportData.data.financialRatios.contributionComplianceRate}%`);
    console.log(`  - Member Participation Rate: ${reportData.data.financialRatios.memberParticipationRate}%`);
    
    console.log('\nFinancial Health:');
    console.log(`  - Overall Health: ${reportData.data.financialHealth.overallHealth}`);
    console.log(`  - Liquidity Health: ${reportData.data.financialHealth.liquidityHealth}`);
    console.log(`  - Risk Health: ${reportData.data.financialHealth.riskHealth}`);
    console.log(`  - Compliance Health: ${reportData.data.financialHealth.complianceHealth}`);
    console.log(`  - Participation Health: ${reportData.data.financialHealth.participationHealth}`);
    
    console.log('\nRecommendations:');
    reportData.data.recommendations.forEach((rec, index) => {
      console.log(`  ${index + 1}. ${rec}`);
    });
    
    console.log('\n=== TEST COMPLETED SUCCESSFULLY ===');
    
  } catch (error) {
    console.error('Error testing comprehensive report:', error);
    console.error(error.stack);
  }
}

// Run the test
testComprehensiveReport();